version: '2'
services:
  webapp:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "80:8080"
    depends_on:
      - db  
    env_file: .env  
  db:
    image: postgres:alpine
    env_file: .env
    volumes:
      - ./data:/var/lib/postgresql/data/acronyms